INSERT INTO TBPRODUTO(
PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES (
'1040107', 'light - 350ml - Melância', 'lata', '350ml', 'Melância', 4.56);

select * from tbproduto;

INSERT INTO TABELA_VENDEDORES (
MATRICULA, NOME, PORCENTUAL_COMISSAO) VALUES (
'00233', 'João Geraldo da Fonseca', 10);

SELECT * FROM TABELA_VENDEDORES;
