USE SUCOS;

INSERT INTO TBPRODUTO(
PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES (
'1037797', 'clean-2Litros-Laranja', 'pet', '2Litros', 'Laranja', 16.01);

INSERT INTO TBPRODUTO(
PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES (
'1000889', 'Sabor Da Montanha - 700ml - Uva', 'Garrafa', '700ml', 'Uva', 6.31);

INSERT INTO TBPRODUTO(
PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES (
'1004327', 'Videira do Campo - 1,5 Litros - Melância', 'Pet', '1.5 Litros', 'Melância', 19.51);

SELECT * FROM TBPRODUTO;

INSERT INTO TABELA_VENDEDORES (
MATRICULA, NOME, PORCENTUAL_COMISSAO) VALUES (
'00235', 'Márcio Almeida Silva', 8);

INSERT INTO TABELA_VENDEDORES (
MATRICULA, NOME, PORCENTUAL_COMISSAO) VALUES (
'00236', 'Cláudia Morais', 8);

SELECT * FROM TABELA_VENDEDORES;
