USE SUCOS;

ALTER TABLE tbproduto ADD PRIMARY KEY (PRODUTO);

DESCRIBE TBPRODUTO;

INSERT INTO TBPRODUTO(
PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES (
'1040107', 'light - 350ml - Melância', 'Garrafa', '350ml', 'Melância', 4.56);

SELECT * FROM tbproduto;