SELECT * FROM tbcliente;
SELECT CPF, NOME, ENDERECO1, ENDERECO2 FROM tbcliente;
SELECT CPF, NOME, ENDERECO1, ENDERECO2 FROM tbcliente LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tbcliente;