# -*- coding: utf-8 -*-
"""Python_para_data_science_primeiros_passos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11cPl1NOVxc_ZW5VCa8tGpYgfHWRj5oSr

# VARIÀVEIS
"""

nome = 'Márcio'

nome

idade = 24

idade

"""# FUNÇÃO"""

# Executar função sempre em parênteses
print(f'O nome é {nome} e sua idade é {idade}')

# Criando minha função
def saudacao():
  nome = input('Qual o Seu Nome: ')
  print(f'Ola {nome}')
saudacao() # Chamada da função

"""# FUNÇÃO COM PARÂMETRO"""

nome = 'Luiza'

def saudacao_com_parametro(nome):
  print(f'Olá: {nome}')
saudacao_com_parametro(nome)

"""# CONDICIONAIS"""

idade = 30
def verifica_se_pode_dirigir(idade):
  if idade >= 18:
    print('Tem Permissão para dirigir')
  else:
    print('Sem Permissão para dirigir')
verifica_se_pode_dirigir(idade)

#CONVERSÃO DE TIPO
def verifica_se_pode_dirigir_sem_parametros():
  idade =  int(input('Qual Sua Idade: '))
  if idade >= 18:
    print('Tem Permissão para dirigir')
  else:
    print('Sem Permissão para dirigir')
verifica_se_pode_dirigir_sem_parametros()

"""# LISTA"""

idade = 22
idade

type(idade)# TIPO DA VARIÁVEL

type('Márcio')

idades = [10,22,15,50]
idades

idades[1]

idades[0:3]

idades[1:]

idades[-1]

type(idades)

"""# LAÇOS E LOOPS"""

def verifica_se_pode_dirigir(idades):
  for idade in idades:
    if idade >= 18:
      print(f'{idade} anos de idade Tem Permissão para dirigir')
    else:
      print(f'{idade} anos idade não Permissão para dirigir')
verifica_se_pode_dirigir(idades)

"""# BOOLEANO"""

idade = 18
idade <= 15

idade >= 18

permissoes = []
idades = [20, 14, 40]

def verifica_se_pode_dirigir(idades, permissoes):
  for idade in idades:
    if idade >= 18:
      permissoes.append(True)
    else:
      permissoes.append(False)
verifica_se_pode_dirigir(idades, permissoes)
permissoes

for permissao in permissoes:
  if permissao:
    print('Pode Dirigir')
  else:
    print('Não Pode Dirigir')

"""# TIPOS EM UMA LISTA"""

lista = ['Marcio', 28, True, '18']
for elemento in lista:
  print(f'O elemeto é do tipo: {type(elemento)}')

"""# IMPORTS"""

from random import randrange

notas_matematicas = []
for nota in range(8):
  notas_matematicas.append(randrange(0,11))
for nota in notas_matematicas:
  print(f'Nota do Aluno: {nota}')

"""# MATPLOT LIB"""

import matplotlib.pyplot as plt

x = list(range(1,9))
y = notas_matematicas
plt.axis([1,8,0,10])
plt.title('Provas e Notas')
plt.plot(x,y)