# -*- coding: utf-8 -*-
"""CAPITULO_3_VISUALIZANDO_DADOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TJoLC5wYYldj8iXxdWIDNulKRlak9b8G

#MATPLOTLIB
"""

from matplotlib import pyplot as plt #impotando a biblioteca

years = [1950, 1960, 1970, 1980, 1990, 2000, 2010]
gdp = [300.2, 543.3, 1075.9, 2862.5, 5979.6, 10289.7, 14958.3]

plt.plot(years,gdp,color = 'green',marker = 'o', linestyle = 'solid') # criar um gráfico

plt.title('Nominal GDP') #adicionar um títulob

plt.ylabel('Billions of $') #adicionr titulo ao eixo y
plt.show()

"""## GRÁFICO DE BARRAS"""

movies = ["Annie Hall", "Ben-Hur", "Casablanca", "Gandhi", "West Side Story"]
num_oscars = [5, 11, 3, 8, 10]

plt.title('My Favorite Movies')
plt.ylabel('# Of Academy Awards')
plt.bar(movies,num_oscars)

"""## HISTOGRAMAS"""

from collections import Counter
grades = [83, 95, 91, 87, 70, 0, 85, 82, 100, 67, 73, 77, 0]
histogram = Counter(min(grade//10*10,90) for grade in grades)
plt.bar([x+5 for x in histogram.keys()],
        histogram.values(),
        10,
        edgecolor=(0,0,0))
plt.axis([-5,105,0,5])
plt.xticks([10*i for i in range(11)])
plt.xlabel('Decile')
plt.ylabel('# of Students')
plt.title('Distribution of Exam 1 Grade')
plt.show()

mentions = [500, 505]
years = [2017, 2018]

plt.xticks(years)
plt.ylabel("# of times i heard someone say 'data science'")
plt.axis([2016.5,2018.5,499,508])
plt.title('Look at this huge Increase!')
plt.bar(years,mentions,0.8,edgecolor=(0,0,0))

"""## GRÁFICO DE LINHAS"""

variance     = [1, 2, 4, 8, 16, 32, 64, 128, 256]
bias_squared = [256, 128, 64, 32, 16, 8, 4, 2, 1]
total_error  = [x + y for x, y in zip(variance, bias_squared)]
xs = [i for i, _ in enumerate(variance)]

# podemos fazer multiplas chamadas para plt.plot
plt.plot(xs,variance,'g-',label='variance')
plt.plot(xs,bias_squared,'r-.',label='bias^2')
plt.plot(xs,total_error,'b:',label='total error')
#criar legenda
plt.legend(loc=9)# loc igual a 9 significa no topo ao centro
plt.xlabel('model complexity')
plt.xticks([])
plt.title('The Bias Variance Tradeoff')
plt.savefig('viz_line_chart.png') #salvar figura - gráfico
plt.show()

"""## GRÁFICOS DE DISPERSÃO"""

friends = [ 70,  65,  72,  63,  71,  64,  60,  64,  67]
minutes = [175, 170, 205, 120, 220, 130, 105, 145, 190]
labels =  ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']

plt.scatter(friends,minutes)
#rotular cada ponto
for label, friend_count, minute_count in zip(labels,friends,minutes):
  plt.annotate(label,
              xy=(friend_count,minute_count), # coloque o rotulo no ponto
              xytext=(5,-5), #levemente deslocado
              textcoords = 'offset points')
plt.title('Daily Minutes vs. Number of Friends')
plt.xlabel('# of friends')
plt.ylabel('Daily minutes spent on the site')
plt.show()

