SELECT current_date();
SELECT current_time();
SELECT current_timestamp();
SELECT YEAR(current_date());
SELECT DAY(current_date());
SELECT monthname(CURRENT_DATE());
SELECT datediff(CURRENT_DATE(),'2019-01-01');
SELECT DATE_SUB(CURRENT_DATE(),INTERVAL 5 DAY);
SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS NOME_DO_DIA, MONTHNAME(DATA_VENDA) AS NOME_DO_MES, YEAR(DATA_VENDA) AS ANO FROM NOTAS_FISCAIS;