/*UNIR CAMPOS IGUAIS E REALIZAR UMA FORMULA NOS VALORES NUEMRICOS*/
/*SUM, MAX, MING, AVG, COUNT - FORMULAS PARA VALORES NUMERICOS*/
SELECT ESTADO, LIMITE_DE_CREDITO FROM tabela_de_clientes;
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabela_de_clientes GROUP BY ESTADO;
SELECT EMBALAGEM, PRECO_DE_LISTA FROM tabela_de_produtos;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM tabela_de_produtos GROUP BY EMBALAGEM;
SELECT EMBALAGEM, COUNT(*) AS CONTADOR FROM tabela_de_produtos GROUP BY EMBALAGEM;
SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) FROM tabela_de_clientes WHERE CIDADE = 'Rio de Janeiro'GROUP BY BAIRRO;
SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes GROUP BY ESTADO, BAIRRO ORDER BY BAIRRO;
SELECT CODIGO_DO_PRODUTO, QUANTIDADE*PRECO AS PRECO_TOTAL FROM itens_notas_fiscais ORDER BY PRECO_TOTAL DESC;
SELECT CODIGO_DO_PRODUTO, MAX(QUANTIDADE) AS QUANTIDADE_MAXIMA FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035';
SELECT CODIGO_DO_PRODUTO, COUNT(*) AS CONTAGEM FROM itens_notas_fiscais  GROUP BY CODIGO_DO_PRODUTO ORDER BY CONTAGEM DESC;


