/*FUNCIONA COMO UM FILTRO QUE SE APLICA A UMA AGRAGAÇÃO*/
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes GROUP BY ESTADO HAVING SOMA_LIMITE > 900000;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR, MIN(PRECO_DE_LISTA) AS MENOR FROM tabela_de_produtos GROUP BY EMBALAGEM;
SELECT CPF, COUNT(*) AS VOLUME_DE_COMPRA FROM notas_fiscais WHERE YEAR(DATA_VENDA) = 2016 GROUP BY CPF HAVING VOLUME_DE_COMPRA > 2000 ORDER BY VOLUME_DE_COMPRA DESC;