/*ORDER BY PODE UTILIZAR DOIS CAMPOS PARA ORDENAÇÃO.*/
/*POR PADRÃO A ORDENAÇÃO É ASC (ASCENDENTE)*/
SELECT * FROM tabela_de_produtos;
SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA;
SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA DESC; 
SELECT * FROM tabela_de_produtos ORDER BY NOME_DO_PRODUTO; 
SELECT * FROM tabela_de_produtos ORDER BY EMBALAGEM, NOME_DO_PRODUTO; 
SELECT * FROM tabela_de_produtos ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO ASC; 
SELECT * FROM tabela_de_produtos WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limão';
SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035'ORDER BY QUANTIDADE DESC