/*QUANTIDADE VENDIDA POR SABOR ANO 2016*/
SELECT VENDAS_SABOR.SABOR, VENDAS_SABOR.ANO, VENDAS_SABOR.QUANTIDADE, (VENDAS_SABOR.QUANTIDADE/VENDA_TOTAL.QUANTIDADE) * 100 AS PERCENTUAL FROM 
(SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDAS_SABOR
INNER JOIN
(SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
ON VENDAS_SABOR.ANO = VENDA_TOTAL.ANO
ORDER BY PERCENTUAL DESC;
