SELECT LTRIM(' OLÁ') AS RESULTADO;
SELECT RTRIM('OLÁ ') AS RESULTADO;
SELECT TRIM(' OLÁ ') AS RESULTADO;
SELECT CONCAT('OLÁ', ' ', 'TUDO BEM ?') AS RESULTADO;
SELECT UPPER('Olá Tudo Bem?') AS RESULTADO;
SELECT SUBSTRING('OLÁ, TUDO BEM?',6,4);
SELECT CONCAT(NOME, '(', CPF, ')') AS RESULTADO FROM tabela_de_clientes;