USE VENDAS_SUCOS;
CREATE TABLE TAB_IDENTITY(
ID INT auto_increment,
DESCRITOR VARCHAR(20),
PRIMARY KEY(ID)
);

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('ola');

SELECT * FROM TAB_IDENTITY;

/****CRIANDO VALORES PADRONIZADOS ****/
/****CRIANDO VALORES PADRONIZADOS ****/
CREATE table TAB_PADRAO(
ID INT AUTO_INCREMENT,
DESCRITOR VARCHAR(30),
ENDERECO VARCHAR(100) NULL,
CIDADE VARCHAR(50) DEFAULT 'RIO DE JANEIRO',
DATA_CRIACAO TIMESTAMP DEFAULT current_timestamp(),
PRIMARY KEY(ID)
);


