USE VENDAS_SUCOS;

ALTER TABLE PRODUTOS RENAME COLUMN SBAOR TO SABOR;

INSERT INTO PRODUTOS (CODIGO, DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA) VALUES('1040170','LIGHT - 350 ML','MELÂNCIA','350 ML','LATA',4.56);

SELECT * FROM PRODUTOS;