USE VENDAS_SUCOS;

SELECT * FROM sucos_vendas.TABELA_DE_PRODUTOS;

SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA AS PRECO_LISTA FROM sucos_vendas.TABELA_DE_PRODUTOS;


SELECT * FROM VENDAS_SUCOS.PRODUTOS;

INSERT INTO PRODUTOS
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR,SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA FROM sucos_vendas.TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM PRODUTOS);

SELECT * FROM PRODUTOS;


INSERT INTO CLIENTES
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, 
VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA FROM SUCOS_VENDAS. TABELA_DE_CLIENTES;

SELECT * FROM CLIENTES;

SELECT * FROM vendedores;
