USE VENDAS_SUCOS;

CREATE TABLE tabela_itens_notas(
	NUMERO VARCHAR(5) NOT NULL,
    CODIGO VARCHAR(10) NOT NULL,
    QUANTIDADE INT NULL,
    PRECO FLOAT NULL,
    PRIMARY KEY(NUMERO,CODIGO),
    CONSTRAINT FK_NOTAS FOREIGN KEY(NUMERO) REFERENCES NOTAS(NUMERO),
    CONSTRAINT FK_CODIGO FOREIGN KEY(CODIGO) REFERENCES PRODUTOS(CODIGO)
);