START TRANSACTION;
SELECT* FROM VENDEDORES;
UPDATE VENDEDORES SET COMISSAO = COMISSAO* 1.15;
SELECT* FROM VENDEDORES;
ROLLBACK;
SELECT* FROM VENDEDORES;

START TRANSACTION;
SELECT* FROM VENDEDORES;
UPDATE VENDEDORES SET COMISSAO = COMISSAO* 1.15;
SELECT* FROM VENDEDORES;
COMMIT;
SELECT* FROM VENDEDORES;

START TRANSACTION;
INSERT INTO `vendas_sucos`.`vendedores`
(`MATRICULA`,
`NOME`,
`BAIRRO`,
`COMISSAO`,
`DATA_ADMISSAO`,
`FERIAS`)
VALUES
('99999',
'João Da Silva',
'Icarai',
0.8,
'2012-01-15',
1);
INSERT INTO `vendas_sucos`.`vendedores`
(`MATRICULA`,
`NOME`,
`BAIRRO`,
`COMISSAO`,
`DATA_ADMISSAO`,
`FERIAS`)
VALUES
('99998',
'João Da Silva 2',
'Icarai',
0.8,
'2012-01-15',
1);
ROLLBACK;
