USE VENDAS_SUCOS;
SELECT * FROM NOTAS;
SELECT * FROM tabela_itens_notas;
SELECT * FROM FATURAMENTO;

UPDATE tabela_itens_notas SET QUANTIDADE = 200
WHERE NUMERO = '0103' AND CODIGO = '1002334';

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_UPDATE AFTER UPDATE ON tabela_itens_notas
FOR EACH ROW BEGIN 
	DELETE FROM FATURAMENTO;
	INSERT INTO FATURAMENTO
	SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM
	NOTAS A INNER JOIN tabela_itens_notas B
	ON A.NUMERO = B.NUMERO
	GROUP BY DATA_VENDA;
END//

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_DELETE AFTER DELETE ON tabela_itens_notas
FOR EACH ROW BEGIN 
	DELETE FROM FATURAMENTO;
	INSERT INTO FATURAMENTO
	SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM
	NOTAS A INNER JOIN tabela_itens_notas B
	ON A.NUMERO = B.NUMERO
	GROUP BY DATA_VENDA;
END//
